[project]
name = "extremeroles"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hypothesis>=6.138.14",
    "lxml>=6.0.1",
    "pylightxl==1.61",
    "pytest>=8.4.1",
    "ruff>=0.12.11",
]
