name: AutoBuildAndTransCheck


on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build_check:
    runs-on: windows-latest
    if: contains(github.event.pull_request.labels.*.name, 'ReadyToMerge')
    steps:
      - name: Generate token
        id: gen_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          submodules: true
      - name: SetupNuget
        uses: nuget/setup-nuget@v2
      - name: RestoreNugetPackage
        run: nuget restore ExtremeRoles.sln
      - name: SetupPython
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
      - name: InstallPythonLibrary
        run: pip install -r requirements.txt
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: AddMsBuildToPATH
        uses: microsoft/setup-msbuild@v2
      - name: RunBuild
        id: build
        continue-on-error: true
        run: msbuild ExtremeRoles.sln -t:restore,build -p:Configuration=Release -p:RestorePackagesConfig=true
      - name: CheckTransData
        continue-on-error: true
        run: python createtransdatareport.py ${{ steps.build.outcome }}
      - name: PostComment
        uses: thollander/actions-comment-pull-request@v3
        with:
            github-token: ${{ steps.gen_token.outputs.token }}
            pr-number: ${{ github.event.number }}
            file-path: .github/workflows/comment.md
