name: CreateReleasePackage


on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'PackageVersion'
        required: true

jobs:
  packing:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: SetupNuget
        uses: nuget/setup-nuget@v2
      - name: RestoreNugetPackage
        run: nuget restore ExtremeRoles.sln
      - name: SetupPython
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: AddMsBuildToPATH
        uses: microsoft/setup-msbuild@v2
      - name: RunBuildAndPacking
        run: ./packing.ps1

      # ExtremeRoles.zip
      - uses: actions/upload-artifact@v4
        with:
          name: "ExtremeRoles-v${{ github.event.inputs.versions }}"
          path: ./workspace/ExtremeRoles/
      # ExtremeRoles-v with skins.zip
      - uses: actions/upload-artifact@v4
        with:
          name: "ExtremeRoles-v${{ github.event.inputs.versions }} with Extreme Skins"
          path: ./workspace/ExtremeRolesWithSkins/
      # STEAM_ONLY_ExtremeRoles.zip
      - uses: actions/upload-artifact@v4
        with:
          name: "STEAM_ONLY_ExtremeRoles-v${{ github.event.inputs.versions }}"
          path: ./workspace/Steam_ExtremeRoles/
      # - STEAM_ExtremeRoles-v with skins.zip
      - uses: actions/upload-artifact@v4
        with:
          name: "STEAM_ONLY_ExtremeRoles-v${{ github.event.inputs.versions }} with Extreme Skins"
          path: ./workspace/Steam_ExtremeRolesWithSkins/
      # Mod zip Only
      - uses: actions/upload-artifact@v4
        with:
          name: ExtremeRolesModOnly
          path: ./workspace/dll/

